.TH SYSMON 1 "February 2026" "sysmon 0.1.0" "User Commands"
.SH NAME
sysmon \- sysmon
.SH SYNOPSIS
.B sysmon
[\fIOPTIONS\fR]
.SH DESCRIPTION
sysmon
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit.
.TP
.B \-v, \-\-version
Show version information and exit.
.SH EXAMPLES
.TP
Run the command:
.B sysmon
.TP
Show help:
.B sysmon \-\-help
.SH SEE ALSO
.BR ms (1)
.SH AUTHOR
 <>
